ktor:
    application:
        modules:
            - com.sevenwonders.ApplicationKt.module
    deployment:
        port: 9090
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
